[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nwm-eval-mgr"
version = "0.0.0"
description = "Tools for conducting simulation evaluation and forecast verification."
readme = "README.md"
maintainers = [
    { name = "Yuqiong Liu", email = "yuqiong.liu@entarian.com" },
]

[project.optional-dependencies]
dev = ["pytest~=8.4.1", "ruff~=0.12.10", "python-dotenv~=1.2.1", "boto3"]
docs = ["sphinx", "numpydoc", "sphinx_rtd_theme", "sphinx_design", "pydata-sphinx-theme", "sphinx-autodoc-typehints", "myst-parser"]

[tool.setuptools]
packages = []

[tool.sphinx]
project = "nwm-eval-mgr"
author = "Yuqiong Liu"

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v"

filterwarnings = [
    "ignore::DeprecationWarning"
]

python_files = "test_*.py *_tests.py"
python_classes = "Test*"
python_functions = "test_*"

markers = [
  "unit: fast unit tests",
  "integration: lightweight pipeline tests",
  "functional: tests that run the full pipeline and check outputs",
  "slow: tests that take a long time (minutes to hours) to run",
]